### ISSUE TITLE
License incompatible with distributing binary only

### ISSUE THREAD

**Issue by fritzlb** [TheRedNe/Art-Net-to-DMX#1]
Hi,

you published your tool under GPL v3 which requires everyone to disclose the source code (you didn’t do that, you just uploaded a windows executable (.exe))
This means that legally speaking probably no one is allowed to use/modify/imprive your tool. 
If this is intentional, please ignore my message. 

Also, git works best with text files for version control. 

Hi,
du hast als Lizenz für dein Tool die GPL v3 angegeben. Die Lizenz erlaubt es jedem, jegliches mit dem Programm zu machen, inklusive ausführen, kompilieren, dekomponieren, verkaufen und anpassen, erfordert jedoch, dass der Code des Programms öffentlich bleibt. Damit soll verhindert werden, dass große Unternehmen sich an Open Source Code bedienen, diesen leicht anpassen und für viel Geld weiterverkaufen, ohne dass die Open Source Community davon profitiert. 
Du hast dein Programm allerdings nur als .exe auf GitHub hochgeladen, das heißt, die Bedingungen der GPL sind nicht erfüllbar. Vermutlich heißt das, dass rein rechtlich niemand dein Programm nutzen darf. 
Außerdem ist git für Textdatein entwickelt und ermöglicht nur dann eine Versionskontrolle. 

Die einfachste Lösung das Problem zu beheben ist vermutlich einfach die Lizenz zu löschen und 1-2 Sätze ins Readme zu schreiben, wofür die Software genutzt werden darf. Besser ist aber eigentlich, den gesamten Code auf GitHub hochzuladen. Dann erfüllt die Lizenz auch ihren Zweck :)
Falls du irgendwelche Fragen hast oder so, antworte gerne hier.

**Comment by fritzlb** [comment]
Ach so, was mir noch auffällt: ich hoffe, dass du ein openJDK nutzt und nicht das Oracle JDK (oder wenn, dass du die Lizenzbedingungen genau gelesen hast). So etwas kann auch rechtliche Probleme geben, wenn man Pech hat

**Comment by TheRedNe** [comment]
Hi,
hab vom dem ganzen Lizenz Zeugs ehrlich gesagt kein Plan. Würde dann einfach mal die Lizenz löschen. Falls du den Source Code willst kann ich dir diesen gerne zur verfügung stellen.
LG

**Comment by fritzlb** [comment]
Perfekt, dann schließe ich den Issue mal :)
